# Generated by Django 4.1.10 on 2023-07-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='submissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('problem_name', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=10)),
                ('code', models.TextField()),
                ('verdict', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='test_case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc_input', models.CharField(max_length=200)),
                ('tc_output', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('problem_id', models.IntegerField(primary_key=True, serialize=False)),
                ('problem_name', models.CharField(max_length=100)),
                ('problem_description', models.TextField()),
                ('test_cases', models.ManyToManyField(to='home.test_case')),
            ],
        ),
    ]
