# Generated by Django 4.1.10 on 2023-07-22 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissions',
            old_name='erdict',
            new_name='verdict',
        ),
    ]
