# Generated by Django 4.1.10 on 2023-07-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_test_case_problem_problem_test_cases'),
    ]

    operations = [
        migrations.CreateModel(
            name='submissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('problem_name', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=10)),
                ('code', models.TextField()),
                ('verdict', models.BooleanField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
